format = """
$directory\
$git_branch\
$git_status\
$fill\
$lua\
$python\
$dotnet\
$docker_context\
$jobs\
$cmd_duration\
$character
"""

[fill]
symbol = ' '

[dotnet]
style = 'bold blue'
detect_extensions = ['csproj', 'fsproj', 'xproj', 'sln', 'slnx']