format = """
$directory\
$git_branch\
$git_status\
$fill\
$dotnet\
$jobs\
$cmd_duration\
$line_break\
$character\
"""

[fill]
symbol = ' '

[dotnet]
style = 'bold blue'
detect_extensions = ['csproj', 'fsproj', 'xproj', 'sln', 'slnx']